### ISSUE TITLE
collecting "other" items

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#41]
Having trouble adding "other" items when running through interview. Like when I want to add an "other" asset, it wants to ask me about other incomes from the ALToolbox code!

It seems I cannot add two "other" items -- like expenses -- because it doesn't ask if there's another.

**Comment by tobyfey** [comment]
The problem where selecting "other" causes income questions to be asked is because the .source attribute is not being set by the original question and it is required in the default question from assembly line.
Expenses doesn't have this problem because the question in the interview sets .source instead of requiring it.
We could make a question for each asset/income/expense list that sets .source instead of requiring it, or we could have a code block that sets .source temporarily (because we would want to overwrite it with a text box like in expenses and income.)

For adding more expenses, should it ask if there is another expense if someone selects other expense or all the time?  We can make .there_is_another code blocks that let you do either.

**Comment by VTskier** [comment]
Thanks! I can meet up at any time if it's helpful. 

> For adding more expenses, should it ask if there is another expense if someone selects other expense or all the time? We can make .there_is_another code blocks that let you do either.

I think we can ask if there is another all the time. I have a feeling that people will suddenly say, oh, yeah, I also pay for x, y and z during the year!

And on this screen
![image](https://github.com/user-attachments/assets/bb741d59-055a-459a-93d7-0e6ad64aad5b)
Can the dropdown default to the "other" choice that I made to get here?

**Comment by VTskier** [comment]
> The problem where selecting "other" causes income questions to be asked is because the .source attribute is not being set by the original question and it is required in the default question from assembly line. Expenses doesn't have this problem because the question in the interview sets .source instead of requiring it. We could make a question for each asset/income/expense list that sets .source instead of requiring it, or we could have a code block that sets .source temporarily (because we would want to overwrite it with a text box like in expenses and income.)

I'm not really following this so I'm not sure which approach is better!

**Comment by tobyfey** [comment]
Adding customized questions should fix the problem.

**Comment by VTskier** [comment]
Thanks. I added a few more issues, which may be related.

**Comment by tobyfey** [comment]
I think I have the functionality you want.  I will explain in the pull request.
