### ISSUE TITLE
id: public benefits display names

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#44]
fyi, I use an x. here and a generic object, but I don't on the other code blocks that follow. I'm not sure which way is the right way!

**Comment by tobyfey** [comment]
I don't think any of the display_name blocks are being used, because any of the ones that aren't generic object but still have an `x` like in `.get(x.source, x.source)` would throw an error if they were.
.display_name is being set by the `move_checks_to_list` function in al_income.py or may be set by validation code.

Generally, you should use generic object: object to avoid duplicate code.  You could use one code block for all of them, if the blocks were actually being used -
```
generic object: ALIncome
code: |
  x.display_name = x.terms_ordered.get(x.source, x.source)
```
If there was a particular type of ALIncome that you wanted to change, you could then do a find and replace for `x.` and replace it with `public_benefits.` for a new code block, and then that would take priority for public_benefits but the original generic object block would still work for any other ALIncome

The most important and easily-made mistake for generic objects is to mix up the too.  The code block you have for public_benefits would work for public_benefits, but it would also work for any other ALIncome object using public_benefits, which is probably what you don't want.

**Comment by VTskier** [comment]
Ah, OK. Feel free to delete that code if it's not needed. Thanks!
