### ISSUE TITLE
real_estate issues

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#73]
During interview:
- If I use the Add button to add other real_estate, I see this:

![image](https://github.com/user-attachments/assets/b40c5d0c-54d1-49b4-b154-b4dafcfb6c69)

- It wants to get the definition of other_assets[0].complete! It does this at the end of the interview when I am waiting for the preview screen to load.

This also recently happened:
- I checked off and entered 3 types of real_estate including "Other"
- at the end of the interview it asked me for details on my "other assets"  -- twice
- I had to enter this info to move on to the preview screen

There's something strange going on with real_estate and other_assets...

**Comment by tobyfey** [comment]
I haven't been able to recreate the problem with the add button, but the fix for issue #76 seemed to have worked for the question about other_assets in the wrong place.  `other_assets.there_are_any `was being switched from false to true by the preview screen, I don't understand why.  But now that other_assets is gathered before the preview screen, it doesn't seem to be an issue, although I need to test more.
