### ISSUE TITLE
Review screen: need to get bank assets to show as None on review screen if all are zero

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#76]

**Comment by tobyfey** [comment]
This seems to be happening because bank_assets isn't being gathered before the review screen.  None of the lists are being gathered by the interview order, but the preview screen seemed to gather all the lists except bank_assets.  I fixed this by changing the interview order from `if bank_assets.there_are_any:` to `if len(bank_assets) > 0` which will make sure it is gathered.  I did this for the other lists too, but I haven't tested thoroughly.
